# 07 - Train LSTM Future Risk Model

This notebook trains an LSTM model using patient-level exam sequences.

Each patient sequence contains exam-level CNN features, asymmetry features, view availability masks, and recency weights. The model predicts 1-year, 2-year, 3-year, 4-year, and 5-year future risk.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# Imports

import os
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split

In [3]:
device = torch.device(
    "cuda" if torch.cuda.is_available()
    else "cpu"
)

In [4]:
# File paths

SEQUENCE_PATH = "/content/drive/MyDrive/EMBED/Features/embed_lstm_patient_sequences.npy"
LABEL_PATH = "/content/drive/MyDrive/EMBED/Features/embed_lstm_patient_labels.npy"
MASK_PATH = "/content/drive/MyDrive/EMBED/Features/embed_lstm_sequence_masks.npy"
METADATA_PATH = "/content/drive/MyDrive/EMBED/Features/embed_lstm_patient_metadata.csv"

MODEL_SAVE_PATH = "/content/drive/MyDrive/EMBED/Models/best_lstm_future_risk.pth"

In [5]:
# Load LSTM-ready data

X = np.load(SEQUENCE_PATH)
y = np.load(LABEL_PATH)
sequence_masks = np.load(MASK_PATH)
metadata = pd.read_csv(METADATA_PATH)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Mask shape:", sequence_masks.shape)
print("Metadata shape:", metadata.shape)

metadata.head()

X shape: (40, 13, 6149)
y shape: (40, 5)
Mask shape: (40, 13)
Metadata shape: (40, 5)

   empi_anon  num_exams first_exam_date last_exam_date  max_sequence_length
0   11057159          7      2013-03-05     2020-03-02                   13
1   11354401          6      2013-12-14     2020-05-21                   13
2   12249159         13      2013-02-22     2020-04-20                   13
3   18069268          2      2018-03-17     2020-05-07                   13
4   18954563          3      2018-04-05     2019-03-04                   13

In [6]:
print("1yr positives:", y[:,0].sum())
print("2yr positives:", y[:,1].sum())
print("3yr positives:", y[:,2].sum())
print("4yr positives:", y[:,3].sum())
print("5yr positives:", y[:,4].sum())

1yr positives: 3.0
2yr positives: 9.0
3yr positives: 14.0
4yr positives: 16.0
5yr positives: 18.0

In [7]:
from sklearn.model_selection import KFold

kfold = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

folds = list(kfold.split(X))

print("Number of folds:", len(folds))

for fold, (train_idx, test_idx) in enumerate(folds, start=1):
    print(f"Fold {fold}")
    print("Train patients:", len(train_idx))
    print("Test patients:", len(test_idx))
    print("Test indices:", test_idx)
    print("-" * 40)

Number of folds: 5
Fold 1
Train patients: 32
Test patients: 8
Test indices: [ 4 12 15 16 19 26 27 37]
----------------------------------------
Fold 2
Train patients: 32
Test patients: 8
Test indices: [ 6  8  9 13 25 31 34 39]
----------------------------------------
Fold 3
Train patients: 32
Test patients: 8
Test indices: [ 0  1  5 11 17 24 29 33]
----------------------------------------
Fold 4
Train patients: 32
Test patients: 8
Test indices: [ 2  3 21 23 30 32 35 36]
----------------------------------------
Fold 5
Train patients: 32
Test patients: 8
Test indices: [ 7 10 14 18 20 22 28 38]
----------------------------------------

In [8]:
class FutureRiskDataset(Dataset):

    def __init__(self, X, y, masks):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)
        self.masks = torch.tensor(masks, dtype=torch.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx], self.masks[idx]

In [9]:
class FutureRiskLSTM(nn.Module):

    def __init__(
        self,
        input_size=6149,
        compressed_size=256,
        hidden_size=128,
        num_layers=1,
        output_size=5,
        dropout=0.3
    ):
        super(FutureRiskLSTM, self).__init__()

        self.feature_compressor = nn.Sequential(
            nn.Linear(input_size, compressed_size),
            nn.ReLU(),
            nn.Dropout(dropout)
        )

        self.lstm = nn.LSTM(
            input_size=compressed_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True
        )

        self.output_head = nn.Sequential(
            nn.Linear(hidden_size, 64),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(64, output_size)
        )

    def forward(self, x, mask):
        x = self.feature_compressor(x)

        lstm_output, _ = self.lstm(x)

        lengths = mask.sum(dim=1).long()
        last_indices = lengths - 1

        batch_indices = torch.arange(
            x.size(0),
            device=x.device
        )

        last_outputs = lstm_output[
            batch_indices,
            last_indices
        ]

        logits = self.output_head(last_outputs)

        return logits

In [10]:
model = FutureRiskLSTM().to(device)

sample_X = torch.tensor(X[:4], dtype=torch.float32).to(device)
sample_mask = torch.tensor(sequence_masks[:4], dtype=torch.float32).to(device)

with torch.no_grad():
    sample_logits = model(sample_X, sample_mask)

print(sample_logits.shape)

torch.Size([4, 5])

In [11]:
def train_one_epoch(model, dataloader, criterion, optimizer, device):
    model.train()
    total_loss = 0

    for X_batch, y_batch, mask_batch in dataloader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)
        mask_batch = mask_batch.to(device)

        optimizer.zero_grad()

        logits = model(X_batch, mask_batch)
        loss = criterion(logits, y_batch)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(dataloader)


def evaluate(model, dataloader, criterion, device):
    model.eval()
    total_loss = 0

    all_probs = []
    all_labels = []

    with torch.no_grad():
        for X_batch, y_batch, mask_batch in dataloader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            mask_batch = mask_batch.to(device)

            logits = model(X_batch, mask_batch)
            loss = criterion(logits, y_batch)

            probs = torch.sigmoid(logits)

            total_loss += loss.item()
            all_probs.append(probs.cpu().numpy())
            all_labels.append(y_batch.cpu().numpy())

    all_probs = np.vstack(all_probs)
    all_labels = np.vstack(all_labels)

    return total_loss / len(dataloader), all_probs, all_labels

In [12]:
num_epochs = 30
fold_results = []

BEST_MODEL_PATH = "/content/drive/MyDrive/EMBED/models/best_lstm_future_risk.pth"

best_overall_loss = float("inf")

for fold, (train_idx, test_idx) in enumerate(folds, start=1):
    print(f"\n===== Fold {fold} =====")

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]
    mask_train, mask_test = sequence_masks[train_idx], sequence_masks[test_idx]

    train_dataset = FutureRiskDataset(X_train, y_train, mask_train)
    test_dataset = FutureRiskDataset(X_test, y_test, mask_test)

    train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False)

    model = FutureRiskLSTM().to(device)

    criterion = nn.BCEWithLogitsLoss()
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=1e-4,
        weight_decay=1e-4
    )

    best_test_loss = float("inf")
    best_probs = None
    best_labels = None

    for epoch in range(num_epochs):
        train_loss = train_one_epoch(
            model,
            train_loader,
            criterion,
            optimizer,
            device
        )

        test_loss, probs, labels = evaluate(
            model,
            test_loader,
            criterion,
            device
        )

        if test_loss < best_test_loss:

          best_test_loss = test_loss

          best_probs = probs
          best_labels = labels

          if test_loss < best_overall_loss:

              best_overall_loss = test_loss

              torch.save(
                  model.state_dict(),
                  BEST_MODEL_PATH
              )

        print(
            f"Saved new best model "
            f"(loss={test_loss:.4f})"
        )

        print(
            f"Epoch {epoch+1:02d}/{num_epochs} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Test Loss: {test_loss:.4f}"
        )

    fold_results.append({
        "fold": fold,
        "best_test_loss": best_test_loss,
        "probs": best_probs,
        "labels": best_labels
    })

print("\nTraining complete.")

===== Fold 1 =====
Saved new best model (loss=0.6791)
Epoch 01/30 | Train Loss: 0.6863 | Test Loss: 0.6791
Saved new best model (loss=0.6650)
Epoch 02/30 | Train Loss: 0.6785 | Test Loss: 0.6650
Saved new best model (loss=0.6529)
Epoch 03/30 | Train Loss: 0.6714 | Test Loss: 0.6529
Saved new best model (loss=0.6394)
Epoch 04/30 | Train Loss: 0.6625 | Test Loss: 0.6394
Saved new best model (loss=0.6224)
Epoch 05/30 | Train Loss: 0.6572 | Test Loss: 0.6224
Saved new best model (loss=0.6052)
Epoch 06/30 | Train Loss: 0.6509 | Test Loss: 0.6052
Saved new best model (loss=0.5932)
Epoch 07/30 | Train Loss: 0.6357 | Test Loss: 0.5932
Saved new best model (loss=0.5789)
Epoch 08/30 | Train Loss: 0.6335 | Test Loss: 0.5789
Saved new best model (loss=0.5603)
Epoch 09/30 | Train Loss: 0.6198 | Test Loss: 0.5603
Saved new best model (loss=0.5412)
Epoch 10/30 | Train Loss: 0.6082 | Test Loss: 0.5412
Saved new best model (loss=0.5288)
Epoch 11/30 | Train Loss: 0.5971 | Test Loss: 0.5288
Saved new best model (loss=0.5271)
Epoch 12/30 | Train Loss: 0.5967 | Test Loss: 0.5271
Saved new best model (loss=0.5119)
Epoch 13/30 | Train Loss: 0.5882 | Test Loss: 0.5119
Saved new best model (loss=0.5007)
Epoch 14/30 | Train Loss: 0.5883 | Test Loss: 0.5007
Saved new best model (loss=0.4968)
Epoch 15/30 | Train Loss: 0.5840 | Test Loss: 0.4968
Saved new best model (loss=0.5009)
Epoch 16/30 | Train Loss: 0.5857 | Test Loss: 0.5009
Saved new best model (loss=0.4979)
Epoch 17/30 | Train Loss: 0.5830 | Test Loss: 0.4979
Saved new best model (loss=0.4919)
Epoch 18/30 | Train Loss: 0.5715 | Test Loss: 0.4919
Saved new best model (loss=0.4890)
Epoch 19/30 | Train Loss: 0.5623 | Test Loss: 0.4890
Saved new best model (loss=0.4865)
Epoch 20/30 | Train Loss: 0.5439 | Test Loss: 0.4865
Saved new best model (loss=0.4850)
Epoch 21/30 | Train Loss: 0.5489 | Test Loss: 0.4850
Saved new best model (loss=0.4819)
Epoch 22/30 | Train Loss: 0.5422 | Test Loss: 0.4819
Saved new best model (loss=0.4897)
Epoch 23/30 | Train Loss: 0.5321 | Test Loss: 0.4897
Saved new best model (loss=0.4716)
Epoch 24/30 | Train Loss: 0.5382 | Test Loss: 0.4716
Saved new best model (loss=0.4817)
Epoch 25/30 | Train Loss: 0.5084 | Test Loss: 0.4817
Saved new best model (loss=0.4744)
Epoch 26/30 | Train Loss: 0.4901 | Test Loss: 0.4744
Saved new best model (loss=0.4892)
Epoch 27/30 | Train Loss: 0.4600 | Test Loss: 0.4892
Saved new best model (loss=0.4795)
Epoch 28/30 | Train Loss: 0.4610 | Test Loss: 0.4795
Saved new best model (loss=0.4622)
Epoch 29/30 | Train Loss: 0.4625 | Test Loss: 0.4622
Saved new best model (loss=0.4924)
Epoch 30/30 | Train Loss: 0.4334 | Test Loss: 0.4924

===== Fold 2 =====
Saved new best model (loss=0.7042)
Epoch 01/30 | Train Loss: 0.6798 | Test Loss: 0.7042
Saved new best model (loss=0.7028)
Epoch 02/30 | Train Loss: 0.6727 | Test Loss: 0.7028
Saved new best model (loss=0.7024)
Epoch 03/30 | Train Loss: 0.6701 | Test Loss: 0.7024
Saved new best model (loss=0.7018)
Epoch 04/30 | Train Loss: 0.6635 | Test Loss: 0.7018
Saved new best model (loss=0.7027)
Epoch 05/30 | Train Loss: 0.6571 | Test Loss: 0.7027
Saved new best model (loss=0.7036)
Epoch 06/30 | Train Loss: 0.6460 | Test Loss: 0.7036
Saved new best model (loss=0.7074)
Epoch 07/30 | Train Loss: 0.6414 | Test Loss: 0.7074
Saved new best model (loss=0.7158)
Epoch 08/30 | Train Loss: 0.6230 | Test Loss: 0.7158
Saved new best model (loss=0.7215)
Epoch 09/30 | Train Loss: 0.6084 | Test Loss: 0.7215
Saved new best model (loss=0.7333)
Epoch 10/30 | Train Loss: 0.5946 | Test Loss: 0.7333
Saved new best model (loss=0.7416)
Epoch 11/30 | Train Loss: 0.5843 | Test Loss: 0.7416
Saved new best model (loss=0.7489)
Epoch 12/30 | Train Loss: 0.5785 | Test Loss: 0.7489
Saved new best model (loss=0.7550)
Epoch 13/30 | Train Loss: 0.5535 | Test Loss: 0.7550
Saved new best model (loss=0.7749)
Epoch 14/30 | Train Loss: 0.5371 | Test Loss: 0.7749
Saved new best model (loss=0.7687)
Epoch 15/30 | Train Loss: 0.5502 | Test Loss: 0.7687
Saved new best model (loss=0.7759)
Epoch 16/30 | Train Loss: 0.5262 | Test Loss: 0.7759
Saved new best model (loss=0.7877)
Epoch 17/30 | Train Loss: 0.5077 | Test Loss: 0.7877
Saved new best model (loss=0.7836)
Epoch 18/30 | Train Loss: 0.4807 | Test Loss: 0.7836
Saved new best model (loss=0.8057)
Epoch 19/30 | Train Loss: 0.4678 | Test Loss: 0.8057
Saved new best model (loss=0.7873)
Epoch 20/30 | Train Loss: 0.4439 | Test Loss: 0.7873
Saved new best model (loss=0.7977)
Epoch 21/30 | Train Loss: 0.4373 | Test Loss: 0.7977
Saved new best model (loss=0.8068)
Epoch 22/30 | Train Loss: 0.4081 | Test Loss: 0.8068
Saved new best model (loss=0.8340)
Epoch 23/30 | Train Loss: 0.4364 | Test Loss: 0.8340
Saved new best model (loss=0.8962)
Epoch 24/30 | Train Loss: 0.3725 | Test Loss: 0.8962
Saved new best model (loss=0.8047)
Epoch 25/30 | Train Loss: 0.3744 | Test Loss: 0.8047
Saved new best model (loss=0.8840)
Epoch 26/30 | Train Loss: 0.3725 | Test Loss: 0.8840
Saved new best model (loss=0.8741)
Epoch 27/30 | Train Loss: 0.3295 | Test Loss: 0.8741
Saved new best model (loss=0.9108)
Epoch 28/30 | Train Loss: 0.3598 | Test Loss: 0.9108
Saved new best model (loss=0.8711)
Epoch 29/30 | Train Loss: 0.3290 | Test Loss: 0.8711
Saved new best model (loss=0.9235)
Epoch 30/30 | Train Loss: 0.3214 | Test Loss: 0.9235

===== Fold 3 =====
Saved new best model (loss=0.6749)
Epoch 01/30 | Train Loss: 0.6849 | Test Loss: 0.6749
Saved new best model (loss=0.6678)
Epoch 02/30 | Train Loss: 0.6783 | Test Loss: 0.6678
Saved new best model (loss=0.6586)
Epoch 03/30 | Train Loss: 0.6732 | Test Loss: 0.6586
Saved new best model (loss=0.6432)
Epoch 04/30 | Train Loss: 0.6664 | Test Loss: 0.6432
Saved new best model (loss=0.6306)
Epoch 05/30 | Train Loss: 0.6603 | Test Loss: 0.6306
Saved new best model (loss=0.6182)
Epoch 06/30 | Train Loss: 0.6450 | Test Loss: 0.6182
Saved new best model (loss=0.6050)
Epoch 07/30 | Train Loss: 0.6339 | Test Loss: 0.6050
Saved new best model (loss=0.5843)
Epoch 08/30 | Train Loss: 0.6248 | Test Loss: 0.5843
Saved new best model (loss=0.5680)
Epoch 09/30 | Train Loss: 0.6197 | Test Loss: 0.5680
Saved new best model (loss=0.5557)
Epoch 10/30 | Train Loss: 0.5994 | Test Loss: 0.5557
Saved new best model (loss=0.5447)
Epoch 11/30 | Train Loss: 0.5799 | Test Loss: 0.5447
Saved new best model (loss=0.5316)
Epoch 12/30 | Train Loss: 0.5988 | Test Loss: 0.5316
Saved new best model (loss=0.5238)
Epoch 13/30 | Train Loss: 0.5773 | Test Loss: 0.5238
Saved new best model (loss=0.5327)
Epoch 14/30 | Train Loss: 0.5923 | Test Loss: 0.5327
Saved new best model (loss=0.5186)
Epoch 15/30 | Train Loss: 0.5927 | Test Loss: 0.5186
Saved new best model (loss=0.5378)
Epoch 16/30 | Train Loss: 0.5661 | Test Loss: 0.5378
Saved new best model (loss=0.4988)
Epoch 17/30 | Train Loss: 0.5643 | Test Loss: 0.4988
Saved new best model (loss=0.5104)
Epoch 18/30 | Train Loss: 0.5438 | Test Loss: 0.5104
Saved new best model (loss=0.4885)
Epoch 19/30 | Train Loss: 0.5244 | Test Loss: 0.4885
Saved new best model (loss=0.4847)
Epoch 20/30 | Train Loss: 0.5377 | Test Loss: 0.4847
Saved new best model (loss=0.4633)
Epoch 21/30 | Train Loss: 0.5318 | Test Loss: 0.4633
Saved new best model (loss=0.4749)
Epoch 22/30 | Train Loss: 0.4972 | Test Loss: 0.4749
Saved new best model (loss=0.4644)
Epoch 23/30 | Train Loss: 0.4873 | Test Loss: 0.4644
Saved new best model (loss=0.4287)
Epoch 24/30 | Train Loss: 0.4682 | Test Loss: 0.4287
Saved new best model (loss=0.4098)
Epoch 25/30 | Train Loss: 0.4603 | Test Loss: 0.4098
Saved new best model (loss=0.4412)
Epoch 26/30 | Train Loss: 0.4461 | Test Loss: 0.4412
Saved new best model (loss=0.3847)
Epoch 27/30 | Train Loss: 0.4242 | Test Loss: 0.3847
Saved new best model (loss=0.4859)
Epoch 28/30 | Train Loss: 0.4216 | Test Loss: 0.4859
Saved new best model (loss=0.3901)
Epoch 29/30 | Train Loss: 0.4172 | Test Loss: 0.3901
Saved new best model (loss=0.4464)
Epoch 30/30 | Train Loss: 0.3996 | Test Loss: 0.4464

===== Fold 4 =====
Saved new best model (loss=0.6819)
Epoch 01/30 | Train Loss: 0.6917 | Test Loss: 0.6819
Saved new best model (loss=0.6718)
Epoch 02/30 | Train Loss: 0.6814 | Test Loss: 0.6718
Saved new best model (loss=0.6562)
Epoch 03/30 | Train Loss: 0.6701 | Test Loss: 0.6562
Saved new best model (loss=0.6387)
Epoch 04/30 | Train Loss: 0.6594 | Test Loss: 0.6387
Saved new best model (loss=0.6224)
Epoch 05/30 | Train Loss: 0.6390 | Test Loss: 0.6224
Saved new best model (loss=0.6067)
Epoch 06/30 | Train Loss: 0.6229 | Test Loss: 0.6067
Saved new best model (loss=0.5946)
Epoch 07/30 | Train Loss: 0.6005 | Test Loss: 0.5946
Saved new best model (loss=0.5857)
Epoch 08/30 | Train Loss: 0.5948 | Test Loss: 0.5857
Saved new best model (loss=0.5788)
Epoch 09/30 | Train Loss: 0.5865 | Test Loss: 0.5788
Saved new best model (loss=0.5742)
Epoch 10/30 | Train Loss: 0.5827 | Test Loss: 0.5742
Saved new best model (loss=0.5725)
Epoch 11/30 | Train Loss: 0.5825 | Test Loss: 0.5725
Saved new best model (loss=0.5711)
Epoch 12/30 | Train Loss: 0.5747 | Test Loss: 0.5711
Saved new best model (loss=0.5692)
Epoch 13/30 | Train Loss: 0.5594 | Test Loss: 0.5692
Saved new best model (loss=0.5673)
Epoch 14/30 | Train Loss: 0.5658 | Test Loss: 0.5673
Saved new best model (loss=0.5660)
Epoch 15/30 | Train Loss: 0.5530 | Test Loss: 0.5660
Saved new best model (loss=0.5643)
Epoch 16/30 | Train Loss: 0.5495 | Test Loss: 0.5643
Saved new best model (loss=0.5607)
Epoch 17/30 | Train Loss: 0.5441 | Test Loss: 0.5607
Saved new best model (loss=0.5553)
Epoch 18/30 | Train Loss: 0.5450 | Test Loss: 0.5553
Saved new best model (loss=0.5508)
Epoch 19/30 | Train Loss: 0.5418 | Test Loss: 0.5508
Saved new best model (loss=0.5455)
Epoch 20/30 | Train Loss: 0.5582 | Test Loss: 0.5455
Saved new best model (loss=0.5374)
Epoch 21/30 | Train Loss: 0.5368 | Test Loss: 0.5374
Saved new best model (loss=0.5346)
Epoch 22/30 | Train Loss: 0.5100 | Test Loss: 0.5346
Saved new best model (loss=0.5201)
Epoch 23/30 | Train Loss: 0.5248 | Test Loss: 0.5201
Saved new best model (loss=0.5048)
Epoch 24/30 | Train Loss: 0.5163 | Test Loss: 0.5048
Saved new best model (loss=0.4966)
Epoch 25/30 | Train Loss: 0.4957 | Test Loss: 0.4966
Saved new best model (loss=0.4986)
Epoch 26/30 | Train Loss: 0.4946 | Test Loss: 0.4986
Saved new best model (loss=0.4836)
Epoch 27/30 | Train Loss: 0.5026 | Test Loss: 0.4836
Saved new best model (loss=0.4731)
Epoch 28/30 | Train Loss: 0.4946 | Test Loss: 0.4731
Saved new best model (loss=0.4548)
Epoch 29/30 | Train Loss: 0.4886 | Test Loss: 0.4548
Saved new best model (loss=0.4337)
Epoch 30/30 | Train Loss: 0.4916 | Test Loss: 0.4337

===== Fold 5 =====
Saved new best model (loss=0.6769)
Epoch 01/30 | Train Loss: 0.6954 | Test Loss: 0.6769
Saved new best model (loss=0.6735)
Epoch 02/30 | Train Loss: 0.6851 | Test Loss: 0.6735
Saved new best model (loss=0.6687)
Epoch 03/30 | Train Loss: 0.6789 | Test Loss: 0.6687
Saved new best model (loss=0.6610)
Epoch 04/30 | Train Loss: 0.6648 | Test Loss: 0.6610
Saved new best model (loss=0.6515)
Epoch 05/30 | Train Loss: 0.6577 | Test Loss: 0.6515
Saved new best model (loss=0.6410)
Epoch 06/30 | Train Loss: 0.6455 | Test Loss: 0.6410
Saved new best model (loss=0.6314)
Epoch 07/30 | Train Loss: 0.6247 | Test Loss: 0.6314
Saved new best model (loss=0.6222)
Epoch 08/30 | Train Loss: 0.6151 | Test Loss: 0.6222
Saved new best model (loss=0.6154)
Epoch 09/30 | Train Loss: 0.6147 | Test Loss: 0.6154
Saved new best model (loss=0.6098)
Epoch 10/30 | Train Loss: 0.6055 | Test Loss: 0.6098
Saved new best model (loss=0.6045)
Epoch 11/30 | Train Loss: 0.5902 | Test Loss: 0.6045
Saved new best model (loss=0.6005)
Epoch 12/30 | Train Loss: 0.5866 | Test Loss: 0.6005
Saved new best model (loss=0.5973)
Epoch 13/30 | Train Loss: 0.5799 | Test Loss: 0.5973
Saved new best model (loss=0.5937)
Epoch 14/30 | Train Loss: 0.6020 | Test Loss: 0.5937
Saved new best model (loss=0.5905)
Epoch 15/30 | Train Loss: 0.5751 | Test Loss: 0.5905
Saved new best model (loss=0.5887)
Epoch 16/30 | Train Loss: 0.5809 | Test Loss: 0.5887
Saved new best model (loss=0.5871)
Epoch 17/30 | Train Loss: 0.5840 | Test Loss: 0.5871
Saved new best model (loss=0.5833)
Epoch 18/30 | Train Loss: 0.5421 | Test Loss: 0.5833
Saved new best model (loss=0.5786)
Epoch 19/30 | Train Loss: 0.5741 | Test Loss: 0.5786
Saved new best model (loss=0.5748)
Epoch 20/30 | Train Loss: 0.5758 | Test Loss: 0.5748
Saved new best model (loss=0.5713)
Epoch 21/30 | Train Loss: 0.5666 | Test Loss: 0.5713
Saved new best model (loss=0.5694)
Epoch 22/30 | Train Loss: 0.5571 | Test Loss: 0.5694
Saved new best model (loss=0.5676)
Epoch 23/30 | Train Loss: 0.5598 | Test Loss: 0.5676
Saved new best model (loss=0.5615)
Epoch 24/30 | Train Loss: 0.5559 | Test Loss: 0.5615
Saved new best model (loss=0.5571)
Epoch 25/30 | Train Loss: 0.5346 | Test Loss: 0.5571
Saved new best model (loss=0.5604)
Epoch 26/30 | Train Loss: 0.5386 | Test Loss: 0.5604
Saved new best model (loss=0.5554)
Epoch 27/30 | Train Loss: 0.5347 | Test Loss: 0.5554
Saved new best model (loss=0.5447)
Epoch 28/30 | Train Loss: 0.5288 | Test Loss: 0.5447
Saved new best model (loss=0.5438)
Epoch 29/30 | Train Loss: 0.5070 | Test Loss: 0.5438
Saved new best model (loss=0.5393)
Epoch 30/30 | Train Loss: 0.4913 | Test Loss: 0.5393

Training complete.

In [13]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

risk_names = ["1yr", "2yr", "3yr", "4yr", "5yr"]

metrics_rows = []

for result in fold_results:
    fold = result["fold"]
    probs = result["probs"]
    labels = result["labels"]

    preds = (probs >= 0.5).astype(int)

    for i, risk_name in enumerate(risk_names):
        y_true = labels[:, i]
        y_pred = preds[:, i]
        y_prob = probs[:, i]

        try:
            auc = roc_auc_score(y_true, y_prob)
        except ValueError:
            auc = np.nan

        metrics_rows.append({
            "fold": fold,
            "risk_window": risk_name,
            "accuracy": accuracy_score(y_true, y_pred),
            "precision": precision_score(y_true, y_pred, zero_division=0),
            "recall": recall_score(y_true, y_pred, zero_division=0),
            "f1": f1_score(y_true, y_pred, zero_division=0),
            "roc_auc": auc
        })

metrics_df = pd.DataFrame(metrics_rows)

metrics_df

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

    fold risk_window  accuracy  precision    recall        f1   roc_auc
0      1         1yr     1.000        0.0  0.000000  0.000000       NaN
1      1         2yr     1.000        0.0  0.000000  0.000000       NaN
2      1         3yr     0.875        0.0  0.000000  0.000000       NaN
3      1         4yr     0.625        0.0  0.000000  0.000000  0.142857
4      1         5yr     0.750        1.0  0.333333  0.500000  0.733333
5      2         1yr     0.750        0.0  0.000000  0.000000  0.750000
6      2         2yr     0.375        0.0  0.000000  0.000000  0.866667
7      2         3yr     0.375        0.0  0.000000  0.000000  0.200000
8      2         4yr     0.375        0.0  0.000000  0.000000  0.133333
9      2         5yr     0.375        0.0  0.000000  0.000000  0.266667
10     3         1yr     0.875        0.0  0.000000  0.000000  1.000000
11     3         2yr     0.875        0.0  0.000000  0.000000  1.000000
12     3         3yr     0.875        0.0  0.000000  0.000000  0.857143
13     3         4yr     0.750        0.0  0.000000  0.000000  1.000000
14     3         5yr     0.875        1.0  0.500000  0.666667  1.000000
15     4         1yr     1.000        0.0  0.000000  0.000000       NaN
16     4         2yr     0.625        0.0  0.000000  0.000000  0.800000
17     4         3yr     0.625        0.0  0.000000  0.000000  1.000000
18     4         4yr     0.875        1.0  0.666667  0.800000  1.000000
19     4         5yr     1.000        1.0  1.000000  1.000000  1.000000
20     5         1yr     1.000        0.0  0.000000  0.000000       NaN
21     5         2yr     1.000        0.0  0.000000  0.000000       NaN
22     5         3yr     0.375        0.0  0.000000  0.000000  0.733333
23     5         4yr     0.375        0.0  0.000000  0.000000  0.800000
24     5         5yr     0.625        1.0  0.400000  0.571429  0.800000

In [14]:
summary_metrics = (
    metrics_df
    .groupby("risk_window")
    [["accuracy", "precision", "recall", "f1", "roc_auc"]]
    .mean()
    .reset_index()
)

summary_metrics

  risk_window  accuracy  precision    recall        f1   roc_auc
0         1yr     0.925        0.0  0.000000  0.000000  0.875000
1         2yr     0.775        0.0  0.000000  0.000000  0.888889
2         3yr     0.625        0.0  0.000000  0.000000  0.697619
3         4yr     0.600        0.2  0.133333  0.160000  0.615238
4         5yr     0.725        0.8  0.446667  0.547619  0.760000